# fly.toml app configuration file generated for liteflix-gw on 2024-11-05T01:20:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'liteflix-gw'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
